### ISSUE TITLE
Plan to support Seurat v3

### ISSUE THREAD

**Issue by ge11232002** [nasqar/SeuratWizard#1]
Many thanks for such neat package. I am just wondering whether you have any plan to support Seurat v3, considering the huge difference between v2 and v3. Of course, Seurat v3 is not officially released yet.

Best,
Ge

**Comment by nasqar** [comment]
Glad to see you find this package useful. We will definitely look to upgrade to v3 sometime in 2019 (dates will depend on time/resources).
Looking at the pre-release notes of v3, there are significant changes especially in function calls, but the overall workflow is more or less still intact. So hopefully upgrading to v3 should be a reasonable effort.

Also feel free to add any feature requests that you might find helpful in the interface.

Thanks

**Comment by ge11232002** [comment]
Glad to know this. Many thanks.

**Comment by nasqar** [comment]
@ge11232002 see https://github.com/nasqar/seuratv3wizard for initial version
