### ISSUE TITLE
perplexity for smaller dataset

### ISSUE THREAD

**Issue by ge11232002** [nasqar/SeuratWizard#2]
Hi,

In `RunTSNE` function, `perplexity=30` is always used. However, it might not be appropriate for smaller dataset, such as smart-Seq2 with less than 100 cells after filtering. Is it possible for you to dynamically assign perplexity value according to cell numbers?

Thanks,
Ge

**Comment by nasqar** [comment]
Do you mean:
a) Just expose it on the UI so that the user can set any perplexity value they would like
Or
b) automatically compute a perplexity value based on the number of cells?

**Comment by ge11232002** [comment]
Either is fine for me. Maybe it’s convenient to do it automatically under the hood and output the perplexity value used. 

Just my opinion.

Ge

**Comment by nasqar** [comment]
Added it on the UI so you can set it to any value when running tsne
