### ISSUE TITLE
RunTSNE: do.fast is no longer used

### ISSUE THREAD

**Issue by ge11232002** [nasqar/SeuratWizard#3]
Hi,

Regarding RunTSNE, it also makes senses to use multi threads. Something like
```R
pbmc <- RunTSNE(object = pbmc, dims.use = input$tsnePCDim1:input$tsnePCDim2,
                      tsne.method="Rtsne",
                      num_threads=parallel::detectCores()/2)
````

**Comment by nasqar** [comment]
Hi,
Yes, we are currently working on supporting v3 of seurat, but since there are significant function changes, we might maintain it on a seperate repo OR release the current version before we upgrade to v3.
We will incorporate the above changes in v3 release.

**Comment by ge11232002** [comment]
In v2, this parameter is not used either. The tutotial from the Seurat website is outdated. It's a good idea to have a separate repo.

**Comment by nasqar** [comment]
Fixed. This should also carry over to v3
