### ISSUE TITLE
how to run it with docker file

### ISSUE THREAD

**Issue by deo999** [nasqar/SeuratWizard#4]
how to run it with docker file

**Comment by deo999** [comment]
after running  docker-compose up getting following error:

ERROR: Service 'seurat_wizard' failed to build: The command '/bin/sh -c conda install -y r-devtools r-shiny r-seurat  r-roxygen
2 r-rcpp r-shinydashboard r-shinycssloaders r-shinyjs r-shinybs r-dt' returned a non-zero code: 1

**Comment by nasqar** [comment]
I updated the dockerfile and readme and also uploaded the image to dockerhub.
You can run it as follows:

`docker run -p 80:80 aymanm/seuratwizard`

**Comment by deo999** [comment]
@nasqar  afteer pu;lling your image i run command and it shows following error:
Error response from daemon: driver failed programming external connect
ivity on endpoint quirky_stonebraker (dcdd285690bb65cb92c8d724575439fbf21db166326ac5cbe8429aee72e214ce): Error starting userlan
d proxy: Bind for 0.0.0.0:80 failed: port is already allocated.

**Comment by deo999** [comment]
hi think there is something wrong with your docker itz showing folloing error
Error response from daemon: driver failed programming external connect
ivity on endpoint quirky_stonebraker (dcdd285690bb65cb92c8d724575439fbf21db166326ac5cbe8429aee72e214ce): Error starting userlan
d proxy: Bind for 0.0.0.0:80 failed: port is already allocated.

**Comment by nasqar** [comment]
The error says that another program is running on port 80. So for example, use this:

`docker run -p 8083:80 aymanm/seuratwizard`

to run on port 8083 instead. If you are running it from your local computer, you can access the app from the browser using this link http://localhost:8083/

**Comment by deo999** [comment]
it not working i tried on other 2 machine also change port??

**Comment by nasqar** [comment]
if you are getting the same error, then the port you are using is busy. I would try a different port.
If you could not get it to work, you can use our online version http://nasqar.abudhabi.nyu.edu/SeuratWizard
