### ISSUE TITLE
cell browser export as the last step?

### ISSUE THREAD

**Issue by maximilianh** [nasqar/SeuratWizard#5]
Hi, great tool! You may want to consider one day the automated created of a single cell browser, see cellbrowser.readthedocs.org or cells.ucsc.edu.

**Comment by nasqar** [comment]
We have added an option for ucsc cellbrowser on SeuratV3 Wizard, see last screenshot here (https://github.com/nasqar/seuratv3wizard)

Thanks for your recommendation, feel free to add any useful feature requests
